id: stairway_room_left
task:
- name: stairway_room_left
  type: waypoint_following
  waypoints:
  - {id: stairway_room_left-point-0, x: 0.75, y: 1.05, yaw: 0, z: 0}
  - {id: stairway_room_left-point-1, x: -2.12, y: 1.49, yaw: 0, z: 0}
  - {id: stairway_room_left-point-2, x: -0.79, y: 9.99, yaw: 0, z: 0}
  - {id: stairway_room_left-point-3, x: 2.08, y: 9.54, yaw: 0, z: 0}
